# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nominallikRcppA <- function(par, data, nodes, weights, numpatt, itemsselect, D = 1L, lambda = 0) {
    .Call(`_regIRT_nominallikRcppA`, par, data, nodes, weights, numpatt, itemsselect, D, lambda)
}

gradnominallikRcppA <- function(par, data, nodes, weights, numpatt, itemsselect, D = 1L, lambda = 0) {
    .Call(`_regIRT_gradnominallikRcppA`, par, data, nodes, weights, numpatt, itemsselect, D, lambda)
}

nominallik_fpenRcppA <- function(par, data, nodes, weights, numpatt, itemsselect, alphaW, adaptive, D = 1L, lambda = 0, eps = 0.001) {
    .Call(`_regIRT_nominallik_fpenRcppA`, par, data, nodes, weights, numpatt, itemsselect, alphaW, adaptive, D, lambda, eps)
}

gradnominallik_fpenRcppA <- function(par, data, nodes, weights, numpatt, itemsselect, alphaW, adaptive, D = 1L, lambda = 0, eps = 0.001) {
    .Call(`_regIRT_gradnominallik_fpenRcppA`, par, data, nodes, weights, numpatt, itemsselect, alphaW, adaptive, D, lambda, eps)
}

nominallikaugRcppA <- function(par, data, nodes, weights, gamma, v, c, numpatt, itemsselect, lambda = 0) {
    .Call(`_regIRT_nominallikaugRcppA`, par, data, nodes, weights, gamma, v, c, numpatt, itemsselect, lambda)
}

gradnominallikaugRcppA <- function(par, data, nodes, weights, gamma, v, c, numpatt, itemsselect, lambda = 0) {
    .Call(`_regIRT_gradnominallikaugRcppA`, par, data, nodes, weights, gamma, v, c, numpatt, itemsselect, lambda)
}

